## YAML Template.
---
services:
  - type: web
    name: tarefas-app
    env: java
    plan: free
    buildCommand: "mvn clean package"
    startCommand: "java -jar target/tarefas-0.0.1-SNAPSHOT.jar"
    branches:
      - main
    autoDeploy: true

